# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
  namespace: luckytree-zwsm
  labels:
    app: cloud-config-server
spec:
  selector:
    matchLabels:
      app: cloud-config-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: cloud-config-server
        image: 192.168.0.14:30016/cloud-config-svr:4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 500Mi
        ports:
        - containerPort: 8888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
spec:
  selector:
    app: cloud-config-server
  ports:
  - port: 8888
    targetPort: 8888
