# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
  namespace: luckytree-zwsm
  labels:
    app: shop-service
spec:
  selector:
    matchLabels:
      app: shop-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: shop-service
        image: 192.168.0.14:30016/shop_svr:15
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 500Mi
        ports:
        - containerPort: 10300
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shop-service-service
spec:
  type: NodePort
  selector:
    app: shop-service
  ports:
  - port: 10300
    targetPort: 10300
    nodePort: 31284
