# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: luckytree-zwsm
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: auth
        image: 192.168.0.14:30016/auth:41
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 500Mi
        ports:
        - containerPort: 10400
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
  - port: 10400
    targetPort: 10400
    # nodePort: 31285
# status:
  # loadBalancer:
    # ingress:
    # - ip: 192.168.0.123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
  name: poom-auth-ingress
spec:
  tls:
  - hosts:
    - poom-api.c0dewave.com
    secretName: secret-https
  rules:
  - host: poom-api.c0dewave.com
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 10400
